### ISSUE TITLE
load_datacls(dict of dicts)

### ISSUE THREAD

**Issue by drernie** [fondat/fondat#3]
I ran into fondat while looking for a way to create Resource APIs out of JSON Schema.

I wonder if it might actually be more efficient for me to define all my data classes as as pure YAML document, then create a 'load_datacls' wrapper that calls make_datacls

```python
def make_datacls(
    cls_name: str,
    fields: Iterable[tuple[str, type] | tuple[str, type, dataclasses.Field]],
    init: bool = True,
    **kwargs,
) -> type:
```
The equivalent YAML would be something like:
```yaml
cls_name:
   init: false
   fields:
     str: type
     str2: type@field(default=5)
   keywords:
    namespace: "{'add_one': lambda self: self.x + 1}"
```
The reason, to be honest, is that I'm not sure we will always fondat (or even Python!) going forward, so I'd rather store data about our schemas as, well, data -- so we can generically reuse it with minimal parsing effort.
